version: 2
updates:
  # Scan root-level dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Scan frontend app dependencies
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"

  # Scan Firebase functions dependencies
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
